version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
      timezone: US/Arizona
    # Disable version updates, only get security updates
    open-pull-requests-limit: 0
    assignees:
      - busma13
      - sotojn
