version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
      timezone: US/Arizona
    open-pull-requests-limit: 3
    assignees:
      - jsnoble
      - godber
      - busma13
      - sotojn
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '>= 17.0.0'
