name: Build and Publish

on:
  release:
    types: [published]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - uses: actions/setup-node@v6
        with:
          # NOTE: Hard Coded Node Version
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm run setup
      - run: pnpm publish --access public --no-git-checks
