name: Build and Publish

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  npm-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # NOTE: Hard Coded Node Version
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn setup
      - run: ./scripts/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
