name: Build and Publish

on:
  release:
    types: [published]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # NOTE: Hard Coded Node Version
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn && yarn setup
      - name: Retrieve version
        run : echo "NEW_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
        id: version
      - run: yarn publish --new-version ${{ steps.version.outputs.NEW_VERSION }} --access public --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
